// Code generated by golok. DO NOT EDIT.

package example

import (
	"fmt"
)

func NewProduct(id int, title string, price float64) *Product {
	return &Product{
		ID:    id,
		Title: title,
		Price: price,
	}
}

// ProductBuilder builds a Product using a fluent API.
type ProductBuilder struct {
	obj Product
}

// NewProductBuilder returns a new, zero-value builder.
func NewProductBuilder() *ProductBuilder {
	return &ProductBuilder{}
}

func (b *ProductBuilder) ID(v int) *ProductBuilder {
	b.obj.ID = v
	return b
}
func (b *ProductBuilder) Title(v string) *ProductBuilder {
	b.obj.Title = v
	return b
}
func (b *ProductBuilder) Price(v float64) *ProductBuilder {
	b.obj.Price = v
	return b
}

// Build returns a pointer to the constructed Product.
func (b *ProductBuilder) Build() *Product {
	c := b.obj
	return &c
}

func (s *Product) String() string {
	return fmt.Sprintf("Product{ID=%v, Title=%v, Price=%v}",
		s.ID, s.Title, s.Price)
}
