// Code generated by golok. DO NOT EDIT.

package example

import (
	"fmt"
)

// ServerOption configures a Server instance.
type ServerOption func(*Server)

// WithHost sets the Host field.
func WithHost(v string) ServerOption {
	return func(s *Server) {
		s.Host = v
	}
}

// WithPort sets the Port field.
func WithPort(v int) ServerOption {
	return func(s *Server) {
		s.Port = v
	}
}

// WithTLS sets the TLS field.
func WithTLS(v bool) ServerOption {
	return func(s *Server) {
		s.TLS = v
	}
}

// NewServer creates a Server with the given options applied.
func NewServer(opts ...ServerOption) *Server {
	s := &Server{}
	for _, opt := range opts {
		opt(s)
	}
	return s
}

func (s *Server) String() string {
	return fmt.Sprintf("Server{Host=%v, Port=%v, TLS=%v}",
		s.Host, s.Port, s.TLS)
}

// Validate checks required fields and returns an error if any are missing.
func (s *Server) Validate() error {
	if s.Host == "" {
		return fmt.Errorf("Server.Host is required")
	}
	return nil
}
