// Code generated by golok. DO NOT EDIT.

package example

import (
	"fmt"
	"reflect"
)

func NewUser(name string, email string, age int) *User {
	return &User{
		Name:  name,
		Email: email,
		Age:   age,
	}
}

func (s *User) GetName() string {
	return s.Name
}

func (s *User) GetEmail() string {
	return s.Email
}

func (s *User) GetAge() int {
	return s.Age
}

func (s *User) SetName(v string) *User {
	s.Name = v
	return s
}

func (s *User) SetEmail(v string) *User {
	s.Email = v
	return s
}

func (s *User) SetAge(v int) *User {
	s.Age = v
	return s
}

func (s *User) String() string {
	return fmt.Sprintf("User{Name=%v, Email=%v, Age=%v}",
		s.Name, s.Email, s.Age)
}

func (s *User) Equal(other *User) bool {
	if other == nil {
		return false
	}
	return reflect.DeepEqual(*s, *other)
}

// Clone returns a shallow copy of User.
// For deep copies of slice/map fields, copy them manually.
func (s *User) Clone() *User {
	c := *s
	return &c
}

func NewProduct(iD int, title string, price float64, tags []string) *Product {
	return &Product{
		ID:    iD,
		Title: title,
		Price: price,
		Tags:  tags,
	}
}

// ProductBuilder builds a Product using a fluent API.
type ProductBuilder struct {
	obj Product
}

// NewProductBuilder returns a new, zero-value builder.
func NewProductBuilder() *ProductBuilder {
	return &ProductBuilder{}
}

func (b *ProductBuilder) ID(v int) *ProductBuilder {
	b.obj.ID = v
	return b
}
func (b *ProductBuilder) Title(v string) *ProductBuilder {
	b.obj.Title = v
	return b
}
func (b *ProductBuilder) Price(v float64) *ProductBuilder {
	b.obj.Price = v
	return b
}
func (b *ProductBuilder) Tags(v []string) *ProductBuilder {
	b.obj.Tags = v
	return b
}

// Build returns a pointer to the constructed Product.
func (b *ProductBuilder) Build() *Product {
	c := b.obj
	return &c
}

func (s *Product) String() string {
	return fmt.Sprintf("Product{ID=%v, Title=%v, Price=%v, Tags=%v}",
		s.ID, s.Title, s.Price, s.Tags)
}
