package generator

import (
	"bytes"
	"go/format"
	"text/template"
	"unicode"

	"github.com/praiseson6065/golok/internal/parser"
)

var funcMap = template.FuncMap{
	// title uppercases the first rune: "name" → "Name", "ID" → "ID"
	"title": func(s string) string {
		if s == "" {
			return ""
		}
		r := []rune(s)
		r[0] = unicode.ToUpper(r[0])
		return string(r)
	},
	// lower lowercases the first rune: "Name" → "name", "ID" → "iD"
	"lower": func(s string) string {
		if s == "" {
			return ""
		}
		r := []rune(s)
		r[0] = unicode.ToLower(r[0])
		return string(r)
	},
	// lbrace / rbrace avoid the {{{ template parsing ambiguity
	"lbrace": func() string { return "{" },
	"rbrace": func() string { return "}" },
}

// Generate produces a complete, formatted Go source file with all requested methods.
func Generate(structs []parser.StructInfo, pkg string) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by golok. DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkg + "\n\n")

	if imps := neededImports(structs); len(imps) > 0 {
		buf.WriteString("import (\n")
		for _, imp := range imps {
			buf.WriteString("\t\"" + imp + "\"\n")
		}
		buf.WriteString(")\n\n")
	}

	for _, s := range structs {
		for _, method := range s.Methods {
			tmplStr, ok := methodTemplates[method]
			if !ok {
				continue
			}
			tmpl, err := template.New(method).Funcs(funcMap).Parse(tmplStr)
			if err != nil {
				return nil, err
			}
			if err := tmpl.Execute(&buf, s); err != nil {
				return nil, err
			}
		}
	}

	// gofmt the output — catches template whitespace issues automatically
	src := buf.Bytes()
	formatted, err := format.Source(src)
	if err != nil {
		// Return raw source so the caller can inspect what went wrong
		return src, nil
	}
	return formatted, nil
}

// neededImports scans all requested methods and returns the imports required.
func neededImports(structs []parser.StructInfo) []string {
	needs := map[string]bool{}
	for _, s := range structs {
		for _, m := range s.Methods {
			switch m {
			case "stringer":
				needs["fmt"] = true
			case "equals":
				needs["reflect"] = true
			}
		}
	}
	// return in stable order
	var imps []string
	for _, imp := range []string{"fmt", "reflect", "encoding/json"} {
		if needs[imp] {
			imps = append(imps, imp)
		}
	}
	return imps
}
