package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"reflect"
	"strings"
	"text/template"
	"unicode"

	"github.com/praiseson6065/golok/internal/parser"
)

var funcMap = template.FuncMap{
	// title uppercases the first rune: "name" → "Name", "ID" → "ID"
	"title": func(s string) string {
		if s == "" {
			return ""
		}
		r := []rune(s)
		r[0] = unicode.ToUpper(r[0])
		return string(r)
	},
	// lower lowercases for use as parameter names:
	//   "Name" → "name", "ID" → "id", "URL" → "url"
	// If the entire string is uppercase, lowercase all of it.
	"lower": func(s string) string {
		if s == "" {
			return ""
		}
		if strings.ToUpper(s) == s {
			return strings.ToLower(s)
		}
		r := []rune(s)
		r[0] = unicode.ToLower(r[0])
		return string(r)
	},
	// lbrace / rbrace avoid the {{{ template parsing ambiguity
	"lbrace": func() string { return "{" },
	"rbrace": func() string { return "}" },
	// isRequired checks whether a field's struct tag contains validate:"required"
	"isRequired": func(tag string) bool {
		tagVal := reflect.StructTag(tag).Get("validate")
		for _, rule := range strings.Split(tagVal, ",") {
			if strings.TrimSpace(rule) == "required" {
				return true
			}
		}
		return false
	},
	// zeroCheck returns a Go expression that checks if a field is its zero value
	"zeroCheck": func(fieldName, fieldType string) string {
		switch {
		case fieldType == "string":
			return fmt.Sprintf(`s.%s == ""`, fieldName)
		case strings.HasPrefix(fieldType, "*"):
			return fmt.Sprintf(`s.%s == nil`, fieldName)
		case strings.HasPrefix(fieldType, "[]"), strings.HasPrefix(fieldType, "map["):
			return fmt.Sprintf(`s.%s == nil`, fieldName)
		case fieldType == "bool":
			return fmt.Sprintf(`!s.%s`, fieldName)
		default: // numeric types: int, float64, etc.
			return fmt.Sprintf(`s.%s == 0`, fieldName)
		}
	},
}

// MapperData is the template context for generating struct-to-struct converters.
type MapperData struct {
	Source       parser.StructInfo
	Target       parser.StructInfo
	CommonFields []parser.FieldInfo // fields present in both structs by name and type
}

// Generate produces a complete, formatted Go source file with all requested methods.
// allStructs includes every struct in the file (annotated or not) for mapper resolution.
func Generate(structs []parser.StructInfo, allStructs map[string]parser.StructInfo, pkg string) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by golok. DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkg + "\n\n")

	if imps := neededImports(structs); len(imps) > 0 {
		buf.WriteString("import (\n")
		for _, imp := range imps {
			buf.WriteString("\t\"" + imp + "\"\n")
		}
		buf.WriteString(")\n\n")
	}


	for _, s := range structs {
		// Generate template-based methods
		for _, method := range s.Methods {
			tmplStr, ok := methodTemplates[method]
			if !ok {
				continue
			}
			tmpl, err := template.New(method).Funcs(funcMap).Parse(tmplStr)
			if err != nil {
				return nil, err
			}
			if err := tmpl.Execute(&buf, s); err != nil {
				return nil, err
			}
		}

		// Generate mapper methods for each mapper target
		for _, targetName := range s.MapperTargets {
			target, ok := allStructs[targetName]
			if !ok {
				// Target struct not found in this file — skip gracefully
				continue
			}
			data := MapperData{
				Source:       s,
				Target:       target,
				CommonFields: findCommonFields(s.Fields, target.Fields),
			}
			tmpl, err := template.New("mapper").Funcs(funcMap).Parse(mapperTemplate)
			if err != nil {
				return nil, err
			}
			if err := tmpl.Execute(&buf, data); err != nil {
				return nil, err
			}
		}
	}

	// gofmt the output — catches template whitespace issues automatically
	src := buf.Bytes()
	formatted, err := format.Source(src)
	if err != nil {
		// Return raw source so the caller can inspect what went wrong
		return src, nil
	}
	return formatted, nil
}

// findCommonFields returns fields that exist in both slices with the same name and type.
func findCommonFields(a, b []parser.FieldInfo) []parser.FieldInfo {
	bMap := make(map[string]string, len(b))
	for _, f := range b {
		bMap[f.Name] = f.Type
	}
	var common []parser.FieldInfo
	for _, f := range a {
		if bType, ok := bMap[f.Name]; ok && bType == f.Type {
			common = append(common, f)
		}
	}
	return common
}


// neededImports scans all requested methods and returns the imports required.
func neededImports(structs []parser.StructInfo) []string {
	needs := map[string]bool{}
	for _, s := range structs {
		for _, m := range s.Methods {
			switch m {
			case "stringer", "validate":
				needs["fmt"] = true
			case "equals":
				needs["reflect"] = true
			case "json":
				needs["encoding/json"] = true
			}
		}
	}
	// return in stable order
	var imps []string
	for _, imp := range []string{"fmt", "reflect", "encoding/json"} {
		if needs[imp] {
			imps = append(imps, imp)
		}
	}
	return imps
}
